#!/bin/bash

# Prunes all re-downloadable Docker and Podman containers.

source 'output.sh'

echo 'Cleaning unused DDEV things …'
DDEV_REPORT=$(which ddev)
if echo "${DDEV_REPORT}" | grep -q '/ddev'; then
  ddev delete images;
  success 'Done.'
else
  echo 'Not installed.';
fi
linefeed

echo 'Pruning unused Docker things …'
DOCKER_REPORT=$(which docker)
if echo "${DOCKER_REPORT}" | grep -q '/docker'; then
  docker system prune;
  success 'Done.'
else
  echo 'Not installed.';
fi
linefeed

echo 'Pruning unused Podman things …'
PODMAN_REPORT=$(which podman)
if echo "${PODMAN_REPORT}" | grep -q '/podman'; then
  podman system prune;
  success 'Done.'
else
  echo 'Not installed.';
fi
