#!/bin/bash

#
# Trims all mounted ext4 partitions.
#

source 'output.sh'

echo 'Trimming all ext4 partitions …'

partitions=$(mount | grep -P "type ext4" | awk '{print $3}')
for partition in $partitions
do
  linefeed
  echo "Trimming ${partition} …"
  time sudo fstrim -v "$partition"
done

linefeed
success 'Done.'
