#!/bin/bash

# Flushes the memory caches and the swap partition/file.
# This usually only is helpful after all caches are flooded by large file operations.

source 'output.sh'

write 'Flushing the memory caches and the swap partition/file …'

sudo su -c "echo 3 > '/proc/sys/vm/drop_caches'" root
sudo swapoff -a && sudo swapon -a

success 'Done.'
