#!/bin/bash

# Sets up a local PHP installation using a PPA, but does not set up Composer.

source 'output.sh'

PHP_VERSION='8.1'
echo 'Installing local PHP …'
sudo add-apt-repository deb https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main
sudo apt-get update
sudo apt-get install -y \
"php${PHP_VERSION}-cli" \
"php${PHP_VERSION}-common" \
"php${PHP_VERSION}-curl" \
"php${PHP_VERSION}-mbstring" \
"php${PHP_VERSION}-xdebug" \
"php${PHP_VERSION}-xml"
success 'Done.'
linefeed
