#!/bin/bash

# Installs DDEV.

source 'output.sh'

setup-containers
linefeed

echo 'Installing DDEV …'
PACKAGE_REPORT=$(dpkg -s ddev)
if echo "$PACKAGE_REPORT" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  # Add DDEV’s GPG key to our keyring
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
  sudo chmod a+r /etc/apt/keyrings/ddev.gpg

  # Add DDEV releases to our package repository
  echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null

  # Update package information and install DDEV
  sudo apt-get update
  sudo apt-get install -y --no-install-recommends --no-install-suggests \
    ddev

  echo 'Installing mkcert …'
  mkcert -install

  success 'Done.'
fi
