#!/bin/bash

# Sets up a local PHP installation without a PPA, but does not set up Composer.

source 'output.sh'

echo 'Installing local PHP …'
sudo apt-get install -y \
"php-cli" \
"php-common" \
"php-curl" \
"php-intl" \
"php-mbstring" \
"php-xdebug" \
"php-xml"
success 'Done.'
linefeed
