#!/bin/bash

# Installs Discord, Slack, Zoom and Signal.

source 'output.sh'

echo 'Installing Discord …'
PACKAGE_REPORT=`dpkg -s discord`
if echo "${PACKAGE_REPORT}" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  source 'install-latest-discord.sh'
fi
linefeed

echo 'Installing Slack …'
PACKAGE_REPORT=`dpkg -s slack-desktop`
if echo "${PACKAGE_REPORT}" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  source 'install-latest-slack.sh'
fi
linefeed

echo 'Installing Zoom …'
PACKAGE_REPORT=`snap list`
if echo "${PACKAGE_REPORT}" | grep -q '^zoom-client '; then
  success 'Already installed.';
else
  sudo snap install zoom-client --edge
  success 'Done.'
fi
linefeed

echo 'Installing Signal …'
PACKAGE_REPORT=`snap list`
if echo "${PACKAGE_REPORT}" | grep -q '^signal-desktop '; then
  success 'Already installed.';
else
  sudo snap install signal-desktop
  success 'Done.'
fi
