#!/bin/bash

# Installs and configures git

source 'output.sh'

echo 'Installing git …'
sudo apt-get install -y --no-install-recommends --no-install-suggests gh git gitk git-core git-lfs bash-completion
success 'Done.'
linefeed

echo 'Configuring git …'
git config --global branch.autosetupmerge always
git config --global branch.autosetuprebase remote
git config --global color.ui auto
git config --global core.autocrlf false
git config --global core.eol lf
git config --global core.precomposeunicode true
git config --global core.quotepath false
git config --global init.defaultbranch main
git config --global pull.rebase true
git config --global push.default simple
git config --global rebase.autostash true
git config --global rerere.enabled true
success 'Done.'
linefeed

BASH_CONFIGURATION_FILE=~/.bashrc
touch "${BASH_CONFIGURATION_FILE}"
CURRENT_DIRECTORY=$(dirname "$0")

echo 'Configuring branch display on the shell …'
if grep -q 'parse_git_branch' "${BASH_CONFIGURATION_FILE}"; then
  success 'Already configured.';
else
  echo '' >> "${BASH_CONFIGURATION_FILE}"
  cat "${CURRENT_DIRECTORY}/bashrc-for-git.dist" >> "${BASH_CONFIGURATION_FILE}"
  success 'Done.'
fi
linefeed

echo 'Configuring Bash autocompletion …'
if grep -q '/usr/share/bash-completion/completions/git' "${BASH_CONFIGURATION_FILE}"; then
  success 'Already configured.';
else
  {
    echo ''
    echo '# Bash autocompletion for git'
    echo 'source /usr/share/bash-completion/completions/git'
  } >> "${BASH_CONFIGURATION_FILE}"
  success 'Done.'
fi
linefeed
