#!/bin/bash

# Installs the most relevant packages for a base system, and sets the most important settings.

source 'output.sh'

update-everything
linefeed

echo 'Installing the most relevant packages …'
sudo apt-get install -y \
  apt-show-versions \
  aptitude \
  ausweisapp2 \
  bash-completion \
  curl \
  deborphan \
  etckeeper \
  fonts-roboto \
  gscan2pdf \
  joe \
  kate \
  krusader \
  ncdu \
  pdfarranger \
  ppa-purge \
  thunderbird \
  thunderbird-locale-de \
  thunderbird-locale-en \
  thunderbird-locale-en-us \
  ttf-mscorefonts-installer \
  wget \
  yakuake
success 'Done.'
linefeed

echo 'Installing supporting packages for Krusader …'
sudo apt-get install -y \
  arj \
  bzip2 \
  coreutils \
  cpio \
  kdiff3 \
  kget \
  krename \
  lhasa \
  p7zip-full \
  rar \
  unace \
  unrar \
  unzip \
  xz-utils \
  zip
success 'Done.'
linefeed

echo 'Installing Google Chrome …'
PACKAGE_REPORT=`dpkg -s google-chrome-stable`
if echo "$PACKAGE_REPORT" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  FILENAME='google-chrome-stable_current_amd64.deb'
  curl -O "https://dl.google.com/linux/direct/${FILENAME}" --output-dir /tmp
  sudo apt install -y "/tmp/${FILENAME}"
  rm "/tmp/${FILENAME}"
  success 'Done.'
fi

echo 'Installing Dropbox …'
PACKAGE_REPORT=`dpkg -s dropbox`
if echo "$PACKAGE_REPORT" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  FILENAME='dropbox_2022.12.05_amd64.deb'
  curl -O "https://linux.dropbox.com/packages/ubuntu/${FILENAME}" --output-dir /tmp
  sudo apt install -y "/tmp/${FILENAME}"
  rm "/tmp/${FILENAME}"
  success 'Done.'
fi
