#!/bin/bash

# Installs the most relevant packages for a base system, and sets the most important settings.

source 'output.sh'

echo 'Updating the package lists and all packages …'
sudo apt-get update -y
sudo apt-get dist-upgrade -y
success 'Done.'
linefeed

echo 'Installing the most relevant packages …'
sudo apt-get install -y \
  aptitude \
  ausweisapp2 \
  bash-completion \
  bzip2 \
  curl \
  deborphan \
  etckeeper \
  fonts-roboto \
  gscan2pdf \
  joe \
  kate \
  krusader \
  ncdu \
  p7zip-full \
  pdfarranger \
  thunderbird \
  thunderbird-locale-de \
  thunderbird-locale-en \
  thunderbird-locale-en-us \
  ttf-mscorefonts-installer \
  wget \
  yakuake
success 'Done.'
linefeed

echo 'Installing Google Chrome …'
INSTALLED_PACKAGES=`dpkg -l`
if echo "$INSTALLED_PACKAGES" | grep -q 'google-chrome-stable'; then
  success 'Already installed.';
else
  FILENAME='google-chrome-stable_current_amd64.deb'
  curl -O "https://dl.google.com/linux/direct/${FILENAME}" --output-dir /tmp
  sudo dpkg -i "/tmp/${FILENAME}"
  sudo apt install -f
  rm "/tmp/${FILENAME}"
  success 'Done.'
fi
