#!/bin/bash

# Installs Docker CE and Docker Compose.

source 'output.sh'

echo 'Installing Docker CE …'
PACKAGE_REPORT=`dpkg -s docker-ce`
if echo "$PACKAGE_REPORT" | grep -q 'install ok installed'; then
  success 'Already installed.';
else
  echo 'Removing old Docker versions …'
  sudo-get apt purge docker docker-engine docker.io 2>/dev/null
  sudo apt-get update
  sudo apt-get install -y ca-certificates curl gnupg

  echo 'Setting up repository …'
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  echo 'Installing Docker CE …'
  sudo apt-get update
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  success 'Done.'
fi
