#!/bin/bash

# Updates all DEB packages and snaps.

source 'output.sh'

echo 'Updating DEB packages …'
sudo aptitude update
sudo aptitude dist-upgrade -y
sudo aptitude clean
success 'Done.'
linefeed

echo 'Updating snaps …'
sudo snap refresh
success 'Done.'
linefeed

echo 'Updating Discord …'
PACKAGE_REPORT=`dpkg -s discord`
if echo "${PACKAGE_REPORT}" | grep -q 'install ok installed'; then
  source 'install-latest-discord.sh'
else
  echo 'Not installed.';
fi
linefeed

echo 'Updating Zoom …'
PACKAGE_REPORT=`dpkg -s zoom`
if echo "${PACKAGE_REPORT}" | grep -q 'install ok installed'; then
  source 'install-latest-zoom.sh'
else
  echo 'Not installed.';
fi
linefeed


echo 'Updating dip …'
GEM_REPORT=`gem search --local '^dip$'`
if echo "${GEM_REPORT}" | grep -q 'dip '; then
  gem update dip --user-install;
  success 'Done.'
else
  echo 'Not installed.';
fi
linefeed

echo 'Updating Composer …'
COMPOSER_REPORT=`which composer`
if echo "${COMPOSER_REPORT}" | grep -q '/composer'; then
  composer selfupdate;
  success 'Done.'
else
  echo 'Not installed.';
fi

